#' Function to update a \strong{smonitor} \code{processes} table with the table
#' generated by \code{\link{summarise_process_entiries}}.
#' 
#' @author Stuart K. Grange
#' 
#' @param con A \strong{smonitor} database connection. 
#' 
#' @param df A tibble/data frame generated by 
#' \code{\link{summarise_process_entiries}}. 
#' 
#' @param progress Should a progress bar be displayed? 
#' 
#' @return Invisible \code{con}.
#' 
#' @seealso \code{\link{summarise_process_entiries}}
#' 
#' @export
update_process_entries <- function(con, df, progress = FALSE) {
  
  # Check input
  stopifnot(c("process", "date_start", "date_end", "n_all") %in% names(df))
  
  # Reset variables to update to NULL
  df %>% 
    glue::glue_data(
      "UPDATE processes 
      SET date_start = NULL, 
      date_end = NULL,
      observation_count = NULL 
      WHERE process = {process}"
    ) %>% 
    databaser::db_execute(con, ., progress = progress)
  
  # Update with values
  df %>% 
    select(-n) %>% 
    rename(observation_count = n_all) %>% 
    mutate(across(c(date_start, date_end), as.numeric)) %>% 
    databaser::build_update_statements("processes", ., where = "process") %>% 
    databaser::db_execute(con, ., progress = progress)
  
  return(invisible(con))
  
}
