#' Function to update a \strong{smonitor} \code{processes} table with the table
#' generated by \code{\link{summarise_process_entiries}}.
#' 
#' @author Stuart K. Grange
#' 
#' @param con A \strong{smonitor} database connection. 
#' 
#' @param df A tibble/data frame generated by 
#' \code{\link{summarise_process_entiries}}. 
#' 
#' @param verbose Should the function give messages? 
#' 
#' @param progress Should a progress bar be displayed? 
#' 
#' @return Invisible \code{con}.
#' 
#' @seealso \code{\link{summarise_process_entiries}}
#' 
#' @export
update_process_entries <- function(con, df, verbose = FALSE, progress = FALSE) {
  
  # Check input
  stopifnot(c("process", "date_start", "date_end", "n_all") %in% names(df))
  
  # Reset the variables which will be updated to NULL
  if (verbose) {
    cli::cli_alert_info(
      "{threadr::cli_date()} Setting `{length(df$process)}` processes' variables to `NULL`..."
    )
  }
  
  # Send a single update statement
  df %>% 
    stringr::str_glue_data(
      "UPDATE processes
       SET date_start = NULL,
       date_end = NULL,
       observation_count = NULL
       WHERE process IN ({stringr::str_c(process, collapse = ',')})"
    ) %>%
    databaser::db_execute(con, ., progress = FALSE)
  
  # Update with values
  # Reset the variables which will be updated to NULL
  if (verbose) {
    cli::cli_alert_info(
      "{threadr::cli_date()} Updating `{length(df$process)}` processes..."
    )
  }
  
  # Send many update statements
  df %>% 
    select(-n) %>% 
    rename(observation_count = n_all) %>% 
    mutate(across(c(date_start, date_end), as.numeric)) %>% 
    databaser::build_update_statements("processes", ., where = "process") %>% 
    databaser::db_execute(con, ., progress = progress)
  
  return(invisible(con))
  
}
